### ISSUE TITLE
Complete the exercise

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m2-evaluacion-intermedia-LorenaBH#1]
Really cool job @LorenaBH  !!!

Here you have a steps guide to complete it ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Let me know if you have any doubts ;)

Go for it!!

**Comment by oneeyedman** [comment]
Hi @LorenaBH,

Here you have some tips to improve the exercise:

- [ ] Remember that every time we use `.innerHTML` or `.value` to get DOM content we receive a string. Sometimes we will need to use something like `parseInt()` to convert it to a number
- [ ] Write your classes/variables/functions in English!
- [ ] Try to use imperative for your commit messages. Ex. - > Fix central text
- [ ] Define a good structure of folders and files for the project
- [ ] Add HTML elements for the game: title, label and input, button, space for feedback (`div`, `p`) and number of trials
- [ ] Use a `label` to define the content of the input
- [ ] Connect the label to the input using the `for` attribute of the label and the `id` of the input

Let me know if you have any doubts ;)

Go for it!!

**Comment by LorenaBH** [comment]
it´s oky?

**Comment by oneeyedman** [comment]
Hi @LorenaBH,

no, it is still not ok. 
You have to **Define a good structure of folders and files for the project** just like we talked yesterday

**Comment by oneeyedman** [comment]
well done @LorenaBH!

Here you have a cool well-done gif:
![well done](https://media.giphy.com/media/9g8PH1MbwTy4o/giphy-downsized.gif)
